data = input("실수를 입력하시오: ")
print(data, type(data))
# print(data, type(data), data + 1.2)
data = eval(input("실수를 입력하시오: "))
print(data, type(data), data + 1.2)
data = float(input("정수를 입력하시오: "))
print(data, type(data), data + 1.2)