string = input("(1,2)처럼 입력하시오 ")
print(string, type(string))
string = eval(input("(1,2)처럼 입력하시오 "))
print(string, type(string))
string = input("[1,2,3,4,5,6]처럼 입력하시오 ")
print(string, type(string))
string = eval(input("[1,2,3,4,5,6]처럼 입력하시오 "))
print(string, type(string))